FROM ubuntu:20.04

WORKDIR /PaddleOCR

RUN set -ex \
	&& apt-get update \
	&& savedAptMark="$(apt-mark showmanual)" \
	&& apt-get update && apt-get install -y --no-install-recommends \
		dpkg-dev \
		gcc \
		libbluetooth-dev \
		libbz2-dev \
		libc6-dev \
		libexpat1-dev \
		libffi-dev \
		libgdbm-dev \
		liblzma-dev \
		libncursesw5-dev \
		libreadline-dev \
		libsqlite3-dev \
		libssl-dev \
		make \
		tk-dev \
		uuid-dev \
		wget \
		xz-utils \
		zlib1g-dev \
		unzip \
	&& pip install certifi==2020.6.20 -i https://mirror.baidu.com/pypi/simple \
	&& pip install paddlepaddle==2.1.3 -i https://mirror.baidu.com/pypi/simple \
	&& pip install opencv-python -i https://mirror.baidu.com/pypi/simple \
	&& pip install paddleocr==2.2 -i https://mirror.baidu.com/pypi/simple \
	&& pip install --upgrade pip -i https://mirror.baidu.com/pypi/simple \
	&& pip install paddlehub --upgrade -i https://mirror.baidu.com/pypi/simple \
	&& pip install -U https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl \
	&& wget https://paddleocr.bj.bcebos.com/dygraph_v2.1/ppocr_img.zip \
	&& unzip ppocr_img.zip \
	&& apt-mark auto '.*' > /dev/null \
	&& apt-mark manual $savedAptMark \
	&& find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec ldd '{}' ';' \
		| awk '/=>/ { print $(NF-1) }' \
		| sort -u \
		| xargs -r dpkg-query --search \
		| cut -d: -f1 \
		| sort -u \
		| xargs -r apt-mark manual \
	# && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
	&& find /usr/local -depth \
		\( \
			\( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
			-o \
			\( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
		\) -exec rm -rf '{}' + \
	&& echo ' \
\nfrom paddleocr import PaddleOCR, draw_ocr \
\nfrom paddleocr import PPStructure, draw_structure_result,save_structure_res \
\ntable_engine = PPStructure(show_log=True) \
\nocr = PaddleOCR(use_angle_cls=True, lang="ch")  \
\nimg_path = "/PaddleOCR/ppocr_img/ch/ch.jpg" \
\nresult = ocr.ocr(img_path,cls=True) \
\
' > test.py \
	&& python test.py \
	&& rm -rf /var/lib/apt/* 



EXPOSE 8868

CMD ["python"]

