# 2022-04-20, test traefik and gitlab
# sudo touch /data/acme.json && chmod 600 /data/acme.json
# ssh-keygen -f ~/.ssh/id_rsa -C 'xxxxx@163.com' -N ''
# version: v1.3
# param: 80 and 443 for web
# param: 10022 for ssh git
# param: domain name: wode.com
# param: email: xxxxx@163.com
version: "3.7"
services:

  traefik:
    image: traefik:v2.6.3
    container_name: traefik
    restart: always
    networks:
      - traefik-public
    ports: 
      - "80:80"
      - "443:443"
      - "10022:23"
    environment: 
      - "TZ=Asia/Shanghai"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/traefik/:/logs/
      - /data/acme.json:/acme.json
    command:
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=false"
      #- "--providers.docker.constraints=LabelRegx(`traefik.constraint-label-stack`, `gitlab.+`)"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.watch=true"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--entrypoints.ssh.address=:23"
      - "--entryPoints.http.forwardedHeaders.trustedIPs=0.0.0.0/0"
      - "--entryPoints.traefik.address=:8080"
      - "--log=true"
      - "--log.level=INFO"
      - "--log.filePath=/logs/traefik.log"
      - "--api=true"
      - "--api.insecure=false"
      - "--ping=true"
      - "--accessLog=true"
      - "--accesslog.filePath=/logs/traefik-access.log"
      - "--accesslog.filters.statuscodes=200,300-302"
      - "--accesslog.filters.minduration=200ms"
      - "--accesslog.filters.retryattempts"
      - "--accesslog.bufferingSize=200"
      - "--accesslog.fields.headers.names.ClientAddr=keep"

      - "--certificatesResolvers.lets-encrypt.acme.httpChallenge=true"
      - "--certificatesResolvers.lets-encrypt.acme.storage=acme.json"
      - "--certificatesResolvers.lets-encrypt.acme.email=xxxxx@163.com"
      - "--certificatesResolvers.lets-encrypt.acme.httpChallenge.entrypoint=http"

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
            memory: 200M

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.constraint-label=traefik_public_tag"
      - "traefik.http.routers.stack-proxy-http.rule=Host(`traefik.wode.com`)"
      - "traefik.http.routers.stack-proxy-http.entrypoints=https"
      - "traefik.http.services.stack-porxy.loadbalancer.server.port=8080"

      # config below domains to https
      - "traefik.http.routers.stack-proxy-http.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.stack-proxy-http.tls.domains[0].main=*.wode.com"
      - "traefik.http.routers.stack-proxy-http.tls.domains[0].sans=wode.com"

      # HTTP REDIRECT
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirect-https.entrypoints=http"
      - "traefik.http.routers.redirect-https.middlewares=redirect-to-https"


  gitlab:
    image: gitlab/gitlab-ce:14.9.1-ce.0
    container_name: my-gitlab
    restart: always
    hostname: git.wode.com
    networks:
      - traefik-public

    environment:
      - TZ=Asia/Shanghai
      - DEBUG=false
      - GITLAB_OMNIBUS_CONFIG=external_url 'http://git.wode.com';gitlab_rails['time_zone']='Asia/Shanghai';gitlab_rails['gitlab_shell_ssh_port']='10022';
      
      # v1.4, optimise if needed.
      #prometheus['enable']=false
      #grafana['enable']=false
      #redis_exporter['enable']=false
      #gitlab_exporter['enable']=false
      #node_exporter['enable']=false
      #postgres_exporter['enable']=false
      #alertmanager['enable']=false
      #prometheus_monitoring['enable']=false

      #puma['worker_processes']=2
      #postgresql['shared_buffers']="128MB"
      #postgresql['max_worker_processes']=4
      #sidekiq['max_concurrency']=5
      #sidekiq['min_concurrency']=1
  
    volumes:
      - "/data/gitlab/etc:/etc/gitlab"
      - "/data/gitlab/log:/var/log/gitlab"
      - "/data/gitlab/opt:/var/opt/gitlab"

    deploy:
      resources:
        limits:
          cpus: '2.50'
          memory: 4000M
        reservations:
            memory: 300M
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.gitlab_insecure.entrypoints=http"
      - "traefik.http.routers.gitlab_insecure.rule=Host(`git.wode.com`)"
      - "traefik.http.routers.gitlab_insecure.middlewares=redirect-to-https@docker"

      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.routers.gitlab.entrypoints=https"
      - "traefik.http.routers.gitlab.rule=Host(`git.wode.com`)"
      - "traefik.http.routers.gitlab.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.gitlab.service=gitlab_service"
      - "traefik.http.services.gitlab_service.loadbalancer.server.port=80"
      
      # 2022-04-27, SSH
      - "traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitlab-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-service"
      - "traefik.tcp.services.gitlab-ssh-service.loadbalancer.server.port=22"

  tomcat:
    image: tomcat:8.5.31-jre8
    restart: always
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.tomcat-frontend-http.entrypoints=https"
      - "traefik.http.routers.tomcat-frontend-http.rule=Host(`tomcat.wode.com`)"
      - "traefik.http.services.tomcat-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.tomcat-frontend-http.tls.certresolver=lets-encrypt"
      

networks:
  traefik-public:
    external: true

