FROM ubuntu:20.04

ENV NODE_VERSION=16.x
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y wget curl net-tools git inetutils-ping apt-utils \
  && curl -sL https://deb.nodesource.com/setup_${NODE_VERSION} | bash - \
  && apt-get install -y nodejs \
  && npm install -g yarn \
  && rm -rf /var/lib/apt/* 
  
CMD ['bash']
